export const texts = {
  en: {
    summary: "Summary",
    presentedTo: "Presented To:",
    presentedOn: "Presented On:",
    preparedBy: "Prepared By:",
    validThrough: "Valid Through:",
    initialInvoice: "Initial Invoice:",
    minimumRetainer: "Minimum Retainer Amount:",
    projectEstimate: "Project Estimate:",
    estimatedHours: "Estimated Hours:",
    projectDescription: "Project Description",
    deliverables: "Deliverables",
    whoWillWork: "Who Will Work On This Project",
    howWeGetStarted: "How We Get Started",
    howYouAreBilled: "How You Are Billed",
    resource: "Resource",
    standardRate: "Standard Rate",
    yourRate: "Your Rate",
    afterHours: "After Hours",
    resourceRate: "1.5x Resource Rate (4 Hour Minimum)",
    howWeKeepGoing: "How We Keep Going",
    availabilityAndSLA: "Availability and SLA",
    estimates: "Estimates",
  },
  es: {
    summary: "Resumen",
    presentedTo: "Presentado a:",
    presentedOn: "Presentado el:",
    preparedBy: "Preparado por:",
    validThrough: "Válido hasta:",
    initialInvoice: "Facturación inicial:",
    minimumRetainer: "Monto mínimo de retención:",
    projectEstimate: "Estimación del proyecto:",
    estimatedHours: "Horas estimadas:",
    projectDescription: "Descripción del proyecto",
    deliverables: "Entregables",
    whoWillWork: "Personal trabajando en el Proyecto",
    howWeGetStarted: "Nuestra forma de trabajo",
    howYouAreBilled: "Cómo se cobrarán las horas",
    resource: "Recurso",
    standardRate: "Tarifa estándar",
    yourRate: "Tu tarifa",
    afterHours: "Horas extras",
    resourceRate: "1.5x la tarifa normal (mínimo de 4 horas)",
    howWeKeepGoing: "Siguientes pasos",
    availabilityAndSLA: "Horarios y acuerdo de servicio (SLA)",
    estimates: "Estimaciones",
  },
};