export const texts = {
  en: {
    summary: "Summary",
    presentedTo: "Presented To:",
    presentedOn: "Presented On:",
    preparedBy: "Prepared By:",
    validThrough: "Valid Through:",
    initialInvoice: "Initial Invoice",
    minimumRetainer: "Minimum Retainer Amount",
    projectEstimate: "Project Estimate",
    estimatedHours: "Estimated Hours",
    projectDescription: "Project Description",
    deliverables: "Deliverables",
    whoWillWork: "Who Will Work On This Project",
    howWeGetStarted: "How We Get Started",
    howYouAreBilled: "How You Are Billed",
    resource: "Resource",
    standardRate: "Standard Rate",
    yourRate: "Your Rate",
    afterHours: "After Hours",
    howWeKeepGoing: "How We Keep Going",
    availabilityAndSLA: "Availability and SLA",
    estimates: "Estimates",
  },
  es: {
    summary: "Resumen",
    presentedTo: "Presentado a:",
    presentedOn: "Presentado el:",
    preparedBy: "Preparado por:",
    validThrough: "Válido hasta:",
    initialInvoice: "Factura inicial",
    minimumRetainer: "Monto mínimo de retención",
    projectEstimate: "Estimación del proyecto",
    estimatedHours: "Horas estimadas",
    projectDescription: "Descripción del proyecto",
    deliverables: "Entregables",
    whoWillWork: "Quién trabajará en este proyecto",
    howWeGetStarted: "Cómo empezamos",
    howYouAreBilled: "Cómo se factura",
    resource: "Recurso",
    standardRate: "Tarifa estándar",
    yourRate: "Tu tarifa",
    afterHours: "Horas extras",
    howWeKeepGoing: "Cómo seguimos",
    availabilityAndSLA: "Disponibilidad y SLA",
    estimates: "Estimaciones",
  },
};