import { StyleSheet } from '@react-pdf/renderer'

export const styles = StyleSheet.create({
    page: {
        padding: '16px 24px',
        fontFamily: 'Montserrat',
    },
    viewContainer: { margin: '6px 0' },
    containerGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    short_text: { fontSize: 8, color: 'gray', fontWeight: '600' },
    general_text: { fontSize: 8, color: 'black', marginBottom: 4, fontWeight: '500' },
    section_title: { color: '#1790c1', fontSize: 14, marginBottom: 4, fontWeight: '600' },
    section_title_2: { color: '#1790c1', fontSize: 14, fontWeight: '600' },
    alert_msg_1: {
        backgroundColor: '#D6EBF0',
        color: '#255365',
        padding: 8,
        fontSize: 8,
        marginBottom: 4,
        fontWeight: '500',
        borderRadius: 2,
    },
    alert_msg_2: {
        backgroundColor: '#FAF1DB',
        color: '#83622D',
        padding: 8,
        fontSize: 8,
        marginBottom: 4,
        marginTop: 4,
        fontWeight: '500',
        borderRadius: 2,
    },
    alert_msg_3: {
        backgroundColor: '#EDECEC',
        color: '#544D5F',
        padding: 8,
        fontSize: 8,
        marginBottom: 4,
        fontWeight: '500',
        borderRadius: 2,
    },
    container: { display: 'flex', flexDirection: 'row', marginTop: 16, gap: 32 },
    container_2: { display: 'flex', flexDirection: 'row', marginTop: 8, gap: 32 },
    column: { flex: 1 },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderBottom: '1 solid #ccc',
        paddingVertical: 4,
    },
    label: { fontSize: 9, fontWeight: 'bold' },
    value: { fontSize: 9, fontWeight: '500' },
    table: {
        // @ts-ignore
        display: 'table',
        width: 'auto',
        marginVertical: 10,
        borderTop: '1 solid #ccc',
        borderLeft: '1 solid #ccc',
    },
    tableRow: { flexDirection: 'row' },
    headerRow: { backgroundColor: '#f0f0f0' },
    tableCol: {
        flex: 1,
        padding: 6,
        borderBottom: '1 solid #ccc',
        borderRight: '1 solid #ccc',
    },
    tableCell: { fontSize: 9, fontWeight: '500' },
    tableCellHeader: { fontSize: 9, fontWeight: 'bold' },
    fullWidthNote: { marginTop: 8, paddingLeft: 4, fontSize: 10 },
    bold: { fontWeight: 700 },
    list_item_text: { fontSize: 8, color: 'black', fontWeight: '500', marginBottom: 2 },
    list_bullet: { fontSize: 12, marginRight: 6, lineHeight: 1.2 },
    logo: { width: 150, marginBottom: 12 },
    headerContainer: { marginBottom: 16 },
});
